knpu_oauth2_client:
  clients:
    # the key "facebook_main" can be anything, it
    # will create a service: "knpu.oauth2.client.facebook_main"
    google:
      # must be "google" - it activates that type!
      type: google
      # add and configure client_id and client_secret in parameters.yml
      client_id: '%env(OAUTH_GOOGLE_ID)%'
      client_secret: '%env(OAUTH_GOOGLE_SECRET)%'
      # a route name you'll create
      redirect_route: connect_google_check
      redirect_params: {}